### PR TITLE
feat: add DRiiiP Keys

### PR DESCRIPTION
**Pull request by GreatWizard**
Add DRiiiP Catalog: https://docs.google.com/document/d/1hIFJszQMhrQgfo0wjpplbWcvcWIAs5y3HwfwrbFI9e4/edit

```shell
# node src/generate.js

- DRiiiP Keys
---- Lil'Dentist : 10 colorways
---- Ronron : 6 colorways
---- Olive : 7 colorways
---- Bleblublubleu : 1 colorways
```

### CODE REVIEW

**Comment by GreatWizard** [comment]
Tests are broken because https://kapcave.nachie.com/api/v1/catalog/list returns 502 x.x"

**Comment by anhthang** [comment]
first line is the image, second line is the colorway name. please fix

**Comment by zekth** [comment]
> first line is the image, second line is the colorway name. please fix

Format does not really matter.

**Comment by anhthang** [comment]
> > first line is the image, second line is the colorway name. please fix
> 
> Format does not really matter.

i dont know that :D it's great for contributors

**Pull request merged**
