### PR TITLE
Add Myth Caps

### PR DESCRIPTION
**Pull request by anhthang**
https://docs.google.com/document/d/1-CkxK7KHUIy9gzJkguA36eC463cBHkNeGfgLa40BKVE/edit?usp=sharing

### CODE REVIEW

**Comment by zekth** [comment]
> Error: Myth Caps failed. Error: This file cannot be exported by the user.

**Comment by anhthang** [comment]
> > Error: Myth Caps failed. Error: This file cannot be exported by the user.

what's that error mean? i still able to view that catalog with private browser

**Comment by zekth** [comment]
> > > Error: Myth Caps failed. Error: This file cannot be exported by the user.
> 
> what's that error mean? i still able to view that catalog with private browser

the document needs to allow the export feature.

**Comment by anhthang** [comment]
> > > > Error: Myth Caps failed. Error: This file cannot be exported by the user.
> > 
> > 
> > what's that error mean? i still able to view that catalog with private browser
> 
> the document needs to allow the export feature.

the owner fixed the issue

**Review by zekth — APPROVED** [review]

**Pull request merged**
